CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(50),
    created_at DATE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
