###
GET http://localhost:8000/projects HTTP/1.1
Accept: application/json
Content-Type: application/json


###

POST http://localhost:8000/projects HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "name": "Learn rust3"
}

###

PATCH http://localhost:8000/projects/5 HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "name": "Learning rust 5"
}

